---
- name: Install Raspberry Pi Connect (desktop)
  hosts: all
  become: true

  tasks:
    - name: Remove rpi-connect-lite if installed
      apt:
        name: rpi-connect-lite
        state: absent

    - name: Install rpi-connect
      apt:
        name: rpi-connect
        state: present
