all:
  hosts:
    pihub:
      ansible_host: "{{ lookup('env', 'PI_HOST') | default('pihub.local', true) }}"
      ansible_user: "{{ lookup('env', 'PI_USER') | default('pi', true) }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY') | default('~/.ssh/pihub', true) }}"
      ansible_become: true
      ansible_become_method: sudo
